version: '2.4'
volumes:
  mozzy:
services:
  mozzy:
    build: ./mozzy
    network_mode: host
    volumes:
      - mozzy:/mosquitto/
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    privileged: true